from flows.cascades.cascades_face_detect_algorithm import CascadesFaceDetectionAlgorithm
from flows.cascades.rotation_detect_algorithm import RotationDetectionAlgorithm
from general.first_success_flow import FirstSuccessFlow
from general.base import IAlgorithm, AlgorithmFlow
