from biomio.algorithms.recognition.processes.cluster_match_process import ClusterMatchingProcess
from biomio.algorithms.recognition.processes.data_detect_process import DataDetectionProcess
# from biomio.algorithms.recognition.processes.iden_process import IdentificationProcess
# from biomio.algorithms.recognition.processes.iden_rest_est_process import IdentificationREProcess
from biomio.algorithms.recognition.processes.main_training_process import MainTrainingProcess
from biomio.algorithms.recognition.processes.rotation_detect_process import RotationDetectionProcess
from biomio.algorithms.recognition.processes.rotation_result_process import RotationResultProcess
from biomio.algorithms.recognition.processes.training_process import TrainingProcess
# from biomio.algorithms.recognition.processes.update_data_struct_process import UpdateDataStructureProcess
